// GERADO por perfil-gamer-src/gerar_dados.py — nao editar na mao
window.DADOS_ATUALIZADOS = "17/08/2026";
window.JOGOS = [
 {
  "id": 1,
  "nome": "FINAL FANTASY XIV - MMO",
  "ano": 2013,
  "horas": 1519,
  "enc": "S",
  "w": 1,
  "motivo": "historia ficou fraca na ultima expansao mas vou comprar a nova expansao que vai reformular um pouco gameplay",
  "genres": "MMORPG, Fantasy",
  "h": 3,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 2,
  "nome": "FINAL FANTASY XV",
  "ano": 2016,
  "horas": 142,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action RPG, Fantasy",
  "h": 2,
  "g": 2,
  "d": 1,
  "ff": 3,
  "v": "Mediano",
  "obs": "2ª walkthrough: DLCs dos personagens. História/combate medianos mas divertia"
 },
 {
  "id": 3,
  "nome": "Assassin's Creed® Valhalla",
  "ano": 2020,
  "horas": 131,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": "Jogado muito por ser gigante + pandemia, não por qualidade"
 },
 {
  "id": 4,
  "nome": "Path of Exile 2",
  "ano": 2024,
  "horas": 250,
  "enc": "S",
  "w": 5,
  "motivo": "",
  "genres": "Action RPG, Hack and Slash",
  "h": 2,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 5,
  "nome": "Diablo IV",
  "ano": 2023,
  "horas": 284,
  "enc": "S",
  "w": 3,
  "motivo": "",
  "genres": "Action RPG, Hack and Slash",
  "h": 3,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 6,
  "nome": "Tom Clancy's The Division™",
  "ano": 2016,
  "horas": 102,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Shooter, Open World",
  "h": "N/A",
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 7,
  "nome": "Crimson Desert",
  "ano": 2026,
  "horas": 136,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Open World",
  "h": 1,
  "g": 4,
  "d": 1,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 8,
  "nome": "ELDEN RING™",
  "ano": 2022,
  "horas": 122,
  "enc": "S",
  "w": 3,
  "motivo": "",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 4,
  "d": 3,
  "ff": 4,
  "v": "Masterpiece",
  "obs": ""
 },
 {
  "id": 9,
  "nome": "FINAL FANTASY XVI",
  "ano": 2023,
  "horas": 114,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action RPG, Fantasy",
  "h": 4,
  "g": 3,
  "d": 1,
  "ff": 4,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 10,
  "nome": "Horizon Forbidden West",
  "ano": 2022,
  "horas": 113,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 4,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Masterpiece",
  "obs": ""
 },
 {
  "id": 11,
  "nome": "The Witcher 3: Wild Hunt",
  "ano": 2015,
  "horas": 161,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action RPG, Open World",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": "Inclui Complete Edition (94h PS4) + base (37h PS4) · Nota revisada 1.5→2.5 jul/2026 (161h + zerado + 2 walkthroughs)"
 },
 {
  "id": 12,
  "nome": "OUTRIDERS",
  "ano": 2021,
  "horas": 111,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Shooter",
  "h": 3,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 13,
  "nome": "Tales of Arise",
  "ano": 2021,
  "horas": 80,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, JRPG",
  "h": 3,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 14,
  "nome": "FINAL FANTASY VII REBIRTH",
  "ano": 2024,
  "horas": 88,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, JRPG",
  "h": 2,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 15,
  "nome": "Red Dead Redemption 2",
  "ano": 2018,
  "horas": 98,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 16,
  "nome": "Tom Clancy's The Division®2",
  "ano": 2019,
  "horas": 115,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Shooter, Open World",
  "h": "N/A",
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 17,
  "nome": "WILD HEARTS",
  "ano": 2023,
  "horas": 74,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Monster Hunter-like",
  "h": "N/A",
  "g": "N/A",
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 18,
  "nome": "Middle-earth: Shadow of Mordor",
  "ano": 2014,
  "horas": 53,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 3,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 19,
  "nome": "Assassin's Creed® Odyssey",
  "ano": 2018,
  "horas": 53,
  "enc": "N",
  "w": 1,
  "motivo": "História chata, gameplay fica muito repetitivo, formula ubisoft",
  "genres": "Action-Adventure, Open World, RPG",
  "h": 1,
  "g": 1,
  "d": 2,
  "ff": 1,
  "v": "Muito Ruim",
  "obs": ""
 },
 {
  "id": 20,
  "nome": "Middle-earth™: Shadow of War™",
  "ano": 2017,
  "horas": 73,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 3,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 21,
  "nome": "Ghost of Yōtei",
  "ano": 2025,
  "horas": 62,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 2,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 22,
  "nome": "Clair Obscur: Expedition 33",
  "ano": 2025,
  "horas": 79,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Turn-Based RPG, JRPG",
  "h": 4,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Masterpiece",
  "obs": "Rezerado jul/2026 (+17h na 2ª walkthrough)"
 },
 {
  "id": 23,
  "nome": "Granblue Fantasy: Relink",
  "ano": 2024,
  "horas": 61,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, JRPG",
  "h": 1,
  "g": 3,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 24,
  "nome": "Monster Hunter: World",
  "ano": 2018,
  "horas": 44,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Monster Hunter",
  "h": 1,
  "g": 2,
  "d": 1,
  "ff": 2,
  "v": "Ruim",
  "obs": "Não gostei do fluxo do jogo, lutas repetidas com os mesmos monstros, genérico"
 },
 {
  "id": 25,
  "nome": "FINAL FANTASY VII REMAKE",
  "ano": 2020,
  "horas": 41,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, JRPG",
  "h": "N/A",
  "g": 3,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 26,
  "nome": "The Last of Us™ Remastered",
  "ano": 2014,
  "horas": 50,
  "enc": "S",
  "w": 3,
  "motivo": "",
  "genres": "Action-Adventure, Survival",
  "h": 4,
  "g": 2,
  "d": 2,
  "ff": 4,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 27,
  "nome": "Assassin's Creed® Shadows",
  "ano": 2025,
  "horas": 45,
  "enc": "#",
  "w": 2,
  "motivo": "",
  "genres": "Action-Adventure, Open World, RPG",
  "h": 2,
  "g": 2,
  "d": 3,
  "ff": 2,
  "v": "Mediano",
  "obs": "Jogando no nightmare no ng+ · Comprado por R$60; últimas 4 missões finalizadas jul/2026"
 },
 {
  "id": 28,
  "nome": "Black Myth: Wukong",
  "ano": 2024,
  "horas": 41,
  "enc": "N",
  "w": 1,
  "motivo": "Parei no ultimo chefe por causa da dificuldade, não consegui passar",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 3,
  "d": 3,
  "ff": 3,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 29,
  "nome": "Dragon Age™: The Veilguard",
  "ano": 2024,
  "horas": 41,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Fantasy",
  "h": 1,
  "g": 3,
  "d": 2,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 30,
  "nome": "DAYS GONE",
  "ano": 2019,
  "horas": 37,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World, Survival",
  "h": 3,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 31,
  "nome": "Hogwarts Legacy",
  "ano": 2023,
  "horas": 63,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action RPG, Open World",
  "h": 2,
  "g": 3,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": "Replay jun/2026 (19h): Gameplay 2→3; zerado no fácil para encerrar; sem completar sides. Replay de jogo finalizado, não retentativa."
 },
 {
  "id": 32,
  "nome": "Battlefield™ 6",
  "ano": 2025,
  "horas": 38,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Shooter, Military",
  "h": "N/A",
  "g": 2,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 33,
  "nome": "Marvel's Spider-Man 2",
  "ano": 2023,
  "horas": 36,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 2,
  "g": 2,
  "d": 1,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 34,
  "nome": "Baldur's Gate 3",
  "ano": 2023,
  "horas": 35,
  "enc": "N",
  "w": 1,
  "motivo": "Dialogos são muito teatrais, história parece que não tem trama única, não me importo com companios, gameplay apesar de dezenas de skill no final das contas fica usando sempre a mesma skill/halidade/tecnica",
  "genres": "Turn-Based RPG, Fantasy",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 1,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 35,
  "nome": "Sekiro™: Shadows Die Twice",
  "ano": 2019,
  "horas": 33,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 4,
  "d": 3,
  "ff": 4,
  "v": "Masterpiece",
  "obs": ""
 },
 {
  "id": 36,
  "nome": "SWORD ART ONLINE Alicization Lycoris",
  "ano": 2020,
  "horas": 31,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, JRPG",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 37,
  "nome": "Cyberpunk 2077",
  "ano": 2020,
  "horas": 30,
  "enc": "N",
  "w": 1,
  "motivo": "Historia bem fraca, gameplay é ok por ser tiro",
  "genres": "Action RPG, Open World, Shooter",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 38,
  "nome": "Assassin's Creed® Origins",
  "ano": 2017,
  "horas": 26,
  "enc": "N",
  "w": 1,
  "motivo": "História chata, gameplay fica muito repetitivo, formula ubisoft",
  "genres": "Action-Adventure, Open World, RPG",
  "h": 1,
  "g": 1,
  "d": 2,
  "ff": 1,
  "v": "Muito Ruim",
  "obs": ""
 },
 {
  "id": 39,
  "nome": "Horizon Zero Dawn",
  "ano": 2017,
  "horas": 25,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 4,
  "g": 3,
  "d": 2,
  "ff": 4,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 40,
  "nome": "Lords of the Fallen",
  "ano": 2023,
  "horas": 28,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 2,
  "d": 3,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 41,
  "nome": "DEATH STRANDING 2: ON THE BEACH",
  "ano": 2025,
  "horas": 27,
  "enc": "N",
  "w": 1,
  "motivo": "gameplay passei nervoso, historia ok, tanto que vi no youtibe depois",
  "genres": "Action, Walking Simulator",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 42,
  "nome": "Demon's Souls",
  "ano": 2020,
  "horas": 26,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 2,
  "d": 3,
  "ff": 3,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 43,
  "nome": "DARK SOULS III",
  "ano": 2016,
  "horas": 24,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 3,
  "d": 3,
  "ff": 3,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 44,
  "nome": "God of War",
  "ano": 2018,
  "horas": 23,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure",
  "h": 3,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 45,
  "nome": "Mass Effect™: Andromeda",
  "ano": 2017,
  "horas": 22,
  "enc": "N",
  "w": 1,
  "motivo": "História e dialogos bem ruim mas gameplay legal",
  "genres": "Action RPG, Sci-Fi, Shooter",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 46,
  "nome": "The Last of Us™ Part II",
  "ano": 2020,
  "horas": 19,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action-Adventure, Survival",
  "h": 4,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Muito Bom",
  "obs": ""
 },
 {
  "id": 47,
  "nome": "Persona 5 Royal",
  "ano": 2019,
  "horas": 19,
  "enc": "N",
  "w": 1,
  "motivo": "muito anime, muito longo, coisas de escola, esse estilo slice of life não gostei",
  "genres": "Turn-Based RPG, JRPG, Slice of Life",
  "h": 1,
  "g": 2,
  "d": 1,
  "ff": 1,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 48,
  "nome": "KINGDOM HEARTS III",
  "ano": 2019,
  "horas": 19,
  "enc": "N",
  "w": 1,
  "motivo": "historia muito.confusa e as.missoes.pareciam tudo filler",
  "genres": "Action RPG, JRPG",
  "h": 1,
  "g": 2,
  "d": 1,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 49,
  "nome": "STAR WARS Jedi: Fallen Order",
  "ano": 2019,
  "horas": 19,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Souls-like",
  "h": 3,
  "g": 3,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 50,
  "nome": "God of War Ragnarök",
  "ano": 2022,
  "horas": 18,
  "enc": "N",
  "w": 1,
  "motivo": "gameplay com atreus chato, chame play ficou muito repetitivo",
  "genres": "Action-Adventure",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 51,
  "nome": "Dragon's Dogma 2",
  "ano": 2024,
  "horas": 18,
  "enc": "N",
  "w": 1,
  "motivo": "nao tem fast travel facil. tem que andar muito de lado para outro em.mesmo cenarios sem nada no caminho ah nao ser os mesmos monstros que lutou dezenas de vezes. Jogo prolonga pela distância mas não faz sentido, nem as paisagens são bonitas como crimson desert é",
  "genres": "Action RPG, Open World",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 1,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 52,
  "nome": "Uncharted 4: A Thief's End™",
  "ano": 2016,
  "horas": 17,
  "enc": "N",
  "w": 1,
  "motivo": "acho que pelo gameplay mas historia boa",
  "genres": "Action-Adventure",
  "h": 3,
  "g": 2,
  "d": 1,
  "ff": 2,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 53,
  "nome": "DEATH STRANDING",
  "ano": 2019,
  "horas": 40,
  "enc": "N",
  "w": 1,
  "motivo": "História confusa, gameplay bem simples, é walking simulator",
  "genres": "Action, Walking Simulator",
  "h": 2,
  "g": 2,
  "d": 1,
  "ff": 1,
  "v": "Ruim",
  "obs": "[Director's Cut PS5] mesma coisa que id 61 é mesmo jogo"
 },
 {
  "id": 54,
  "nome": "Star Wars Outlaws",
  "ano": 2024,
  "horas": 17,
  "enc": "N",
  "w": 1,
  "motivo": "história fraca, gameplay fraco, muito espaço vazio de.transaicao entre missoes",
  "genres": "Action-Adventure, Open World",
  "h": 1,
  "g": 1,
  "d": 1,
  "ff": 1,
  "v": "Muito Ruim",
  "obs": "",
  "gratis": true
 },
 {
  "id": 55,
  "nome": "Kingdom Come: Deliverance II",
  "ano": 2025,
  "horas": 16,
  "enc": "N",
  "w": 1,
  "motivo": "estava gostando bastante no começo.  depois o realismo ficou muito cansativo. fica craftango coisas manuais ou amdar.muito. Muito realismo. Historia acabei vendo final youtube",
  "genres": "Action RPG, Open World, Realistic",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 56,
  "nome": "Kena: Bridge of Spirits",
  "ano": 2021,
  "horas": 16,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure",
  "h": 3,
  "g": 3,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 57,
  "nome": "Avowed",
  "ano": 2025,
  "horas": 16,
  "enc": "N",
  "w": 1,
  "motivo": "joguei bastante. nao sei ao certo porque desisto. Lembro de passar raiva ma dificuldade path of damed que é dificuldade mais dificil. dialogos e historia tambem nao eram interessantes",
  "genres": "Action RPG, Fantasy",
  "h": 1,
  "g": 3,
  "d": 3,
  "ff": 2,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 58,
  "nome": "DETROIT: BECOME HUMAN",
  "ano": 2018,
  "horas": 13,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Adventure, Narrative",
  "h": 4,
  "g": 3,
  "d": 1,
  "ff": 4,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 59,
  "nome": "PRAGMATA",
  "ano": 2026,
  "horas": 13,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Sci-Fi",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 60,
  "nome": "Ghost of Tsushima",
  "ano": 2020,
  "horas": 65,
  "enc": "S",
  "w": 2,
  "motivo": "",
  "genres": "Action-Adventure, Open World",
  "h": 4,
  "g": 4,
  "d": 2,
  "ff": 4,
  "v": "Masterpiece",
  "obs": "Top 3 de todos os tempos; 2 walkthroughs completas"
 },
 {
  "id": 61,
  "nome": "Resident Evil 4",
  "ano": 2023,
  "horas": 12,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Survival Horror, Shooter",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 62,
  "nome": "The First Berserker: Khazan",
  "ano": 2025,
  "horas": 12,
  "enc": "N",
  "w": 1,
  "motivo": "passei muita raiva achei muito dificil.  Combate tambem.nao me.pegou muito apesar de.nao ser.ruim",
  "genres": "Action RPG, Souls-like",
  "h": "N/A",
  "g": 2,
  "d": 3,
  "ff": 2,
  "v": "Mediano",
  "obs": ""
 },
 {
  "id": 63,
  "nome": "Avatar: Frontiers of Pandora™",
  "ano": 2023,
  "horas": 12,
  "enc": "N",
  "w": 1,
  "motivo": "missoes nao claras de onde tinha que ir. ireo me.irritou de ficar procurando onde estava as missões.  historia fraca",
  "genres": "Action-Adventure, Open World",
  "h": 1,
  "g": 2,
  "d": 1,
  "ff": 1,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 64,
  "nome": "Resident Evil Requiem",
  "ano": 2026,
  "horas": 12,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Survival Horror",
  "h": 3,
  "g": 3,
  "d": 1,
  "ff": 4,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 65,
  "nome": "Mass Effect: Legendary Edition",
  "ano": 2021,
  "horas": 18,
  "enc": "N",
  "w": 1,
  "motivo": "muito datado",
  "genres": "Action RPG, Sci-Fi, Shooter",
  "h": 2,
  "g": 1,
  "d": 1,
  "ff": 1,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 66,
  "nome": "FINAL FANTASY XII THE ZODIAC AGE",
  "ano": 2017,
  "horas": 11,
  "enc": "N",
  "w": 1,
  "motivo": "não tem pontos fáceis de onde tem que ir, não tem fast travel ilimitada, não tenho paciência pra mundo aberto em que precisa descobrir onde tem que ir. Esse não chega a ser mundo aberto mas mapas são bem grandes",
  "genres": "Turn-Based RPG, JRPG",
  "h": 1,
  "g": 2,
  "d": 2,
  "ff": 2,
  "v": "Ruim",
  "obs": ""
 },
 {
  "id": 67,
  "nome": "The Order: 1886",
  "ano": 2015,
  "horas": 9,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Shooter",
  "h": 3,
  "g": 2,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": "",
  "gratis": true
 },
 {
  "id": 68,
  "nome": "RESIDENT EVIL 2",
  "ano": 2019,
  "horas": 9,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Survival Horror",
  "h": 2,
  "g": 2,
  "d": 2,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 70,
  "nome": "A Way Out",
  "ano": 2018,
  "horas": 6,
  "enc": "S",
  "w": 1,
  "motivo": "",
  "genres": "Action-Adventure, Co-op",
  "h": 3,
  "g": 2,
  "d": 1,
  "ff": 3,
  "v": "Bom",
  "obs": ""
 },
 {
  "id": 71,
  "nome": "NieR:Automata",
  "ano": 2017,
  "horas": 5,
  "enc": "N",
  "w": 1,
  "motivo": "Acho que era pela história fraca",
  "genres": "Action RPG, Hack and Slash",
  "h": 1,
  "g": 1,
  "d": 2,
  "ff": 1,
  "v": "Muito Ruim",
  "obs": ""
 },
 {
  "id": 72,
  "nome": "Wuchang: Fallen Feathers",
  "ano": 2025,
  "horas": 0.5,
  "enc": "N",
  "w": 1,
  "motivo": "Souls-like não-FromSoft; corrida da morte punitiva (repetir trajeto longo até o ponto de morte). Viola aversão a perder tempo/progresso.",
  "genres": "Souls-like / Action RPG",
  "h": 1,
  "g": 1,
  "d": 3,
  "ff": 1,
  "v": "Muito Ruim",
  "obs": "PS Plus grátis jun/2026. Dropado em ~30 min. Padrão confirmado: souls-like não-FromSoft decepciona.",
  "gratis": true
 },
 {
  "id": 73,
  "nome": "Assassin's Creed® IV Black Flag Resync",
  "ano": 2026,
  "horas": 13,
  "enc": "N",
  "w": 1,
  "motivo": "Combate muito simples; navegação (core do jogo) horrível; escrita das cutscenes boa mas história não pegou — final visto no YouTube",
  "genres": "Action-Adventure, Open World, Naval",
  "h": 1,
  "g": 1,
  "d": 1,
  "ff": 1,
  "v": "Ruim",
  "obs": "Jogadas 9h + 4h = 13h total. Dropado jul/2026"
 }
];
window.PLANO = [
 {
  "jogo": "007 First Light",
  "lanc": "Jun/26",
  "est": "15h",
  "status": "—"
 },
 {
  "jogo": "AC Black Flag Resync",
  "lanc": "09/Jul",
  "est": "45h",
  "status": "❌ Dropado com 13h (jul/26) — liberou ~32h"
 },
 {
  "jogo": "Beast of Reincarnation",
  "lanc": "05/Ago",
  "est": "45h",
  "status": "Próximo"
 },
 {
  "jogo": "Lord of the Fallen 2",
  "lanc": "10/Ago",
  "est": "40h",
  "status": "Sugerido p/ Setembro"
 },
 {
  "jogo": "Blood of Dawn",
  "lanc": "03/Set",
  "est": "45h",
  "status": "Outubro"
 },
 {
  "jogo": "Wolverine",
  "lanc": "15/Set",
  "est": "25h",
  "status": "Novembro"
 },
 {
  "jogo": "Phantom Blade",
  "lanc": "08/Set",
  "est": "50h",
  "status": "Nov–Dez"
 }
];
window.NOTAS_PLANO = [
 "Disponibilidade: ~12h/semana (~52h/mês; setembro reduzido ~34h por férias 08–27/09)",
 "Em andamento (jul/26): AC Shadows NG+ nightmare (comprado R$60) · Exp33 rezerado (+17h)",
 "FF14: assinatura pausada; retorno out/nov 2026 antes da expansão Evercold (jan/2027)"
];
